services:
  go-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: go-server
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      # Add other environment variables here directly instead of using env_file

  client-webapp:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client-webapp
    ports:
      - "8081:80"
    depends_on:
      - go-server
